python3 main.py &> prism_results/results_0.txt
python3 main.py &> prism_results/results_1.txt
python3 main.py &> prism_results/results_2.txt
python3 main.py &> prism_results/results_3.txt
python3 main.py &> prism_results/results_4.txt
python3 main.py &> prism_results/results_5.txt
python3 main.py &> prism_results/results_6.txt
python3 main.py &> prism_results/results_7.txt
python3 main.py &> prism_results/results_8.txt
python3 main.py &> prism_results/results_9.txt

python3 main.py &> prism_results/results_10.txt
python3 main.py &> prism_results/results_11.txt
python3 main.py &> prism_results/results_12.txt
python3 main.py &> prism_results/results_13.txt
python3 main.py &> prism_results/results_14.txt
python3 main.py &> prism_results/results_15.txt
python3 main.py &> prism_results/results_16.txt
python3 main.py &> prism_results/results_17.txt
python3 main.py &> prism_results/results_18.txt
python3 main.py &> prism_results/results_19.txt

python3 main.py &> prism_results/results_20.txt
python3 main.py &> prism_results/results_21.txt
python3 main.py &> prism_results/results_22.txt
python3 main.py &> prism_results/results_23.txt
python3 main.py &> prism_results/results_24.txt
python3 main.py &> prism_results/results_25.txt
python3 main.py &> prism_results/results_26.txt
python3 main.py &> prism_results/results_27.txt
python3 main.py &> prism_results/results_28.txt
python3 main.py &> prism_results/results_29.txt

python3 main.py &> prism_results/results_30.txt
python3 main.py &> prism_results/results_31.txt
python3 main.py &> prism_results/results_32.txt
python3 main.py &> prism_results/results_33.txt
python3 main.py &> prism_results/results_34.txt
python3 main.py &> prism_results/results_35.txt
python3 main.py &> prism_results/results_36.txt
python3 main.py &> prism_results/results_37.txt
python3 main.py &> prism_results/results_38.txt
python3 main.py &> prism_results/results_39.txt

python3 main.py &> prism_results/results_40.txt
python3 main.py &> prism_results/results_41.txt
python3 main.py &> prism_results/results_42.txt
python3 main.py &> prism_results/results_43.txt
python3 main.py &> prism_results/results_44.txt
python3 main.py &> prism_results/results_45.txt
python3 main.py &> prism_results/results_46.txt
python3 main.py &> prism_results/results_47.txt
python3 main.py &> prism_results/results_48.txt
python3 main.py &> prism_results/results_49.txt